camera_enabled: true
model: "phone_yolov5s_batch_2_epochs_10_best.onnx"
model_directory: "model/"
classes: "phone_yolov5s_batch_2_epochs_10_best_classes.txt"
classes_directory: "model/"
detection_classes: "phone"
flight_on_found: "pause"
flight_pause_duration: 3
camera_on_found: "cooldown"
camera_on_found_duration: 3
telegram_on_found: "cooldown"
telegram_on_found_duration: 3
esp_on_found: "cooldown"
esp_on_found_duration: 3