flight_enabled: true
default_height: 1
default_velocity: 0.1
default_hold_time: 2
default_yaw_rate: 72.0
initial_pause_duration: 5
logging_decimal_places: 2
led_blink_duration: 2
logs_directory: "logs/"